import type { Atendimento } from "./types";

export const SEED: Atendimento[] = [
  {
    id: "demo-1",
    nome: "Amara N.",
    nacionalidade: "Haiti",
    idioma: "Francês",
    contato: "(11) 9 xxxx-1290",
    acolhedor: "Marina",
    situacaoDocumental: "Em processo de regularização",
    demandas: ["documentacao", "trabalho"],
    respostas: {
      "documentacao.situacao": "Regularização em andamento, aguardando protocolo",
      "documentacao.prazo": "Não",
      "trabalho.trabalhando": "Não",
      "trabalho.necessidade": "Busca por oportunidade formal",
    },
    prioridade: "atencao",
    responsavel: "Marina",
    observacoes: "Retornar com orientação sobre emissão de CPF.",
    status: "novo",
    criadoEm: "2026-09-03T13:10:00.000Z",
    demo: true,
  },
  {
    id: "demo-2",
    nome: "Yusuf A.",
    nacionalidade: "Síria",
    idioma: "Árabe",
    acolhedor: "Tiago",
    situacaoDocumental: "Solicitação de refúgio",
    demandas: ["refugio", "diploma", "educacao"],
    respostas: {
      "refugio.situacao": "Solicitação protocolada há quatro meses",
      "refugio.prazo": "Sim",
      "diploma.pais": "Síria",
      "diploma.nivel": "Graduação",
      "diploma.possui": "Parcialmente",
      "diploma.objetivo": "Revalidação",
      "educacao.nivel": "Superior",
      "educacao.necessidade": "Curso de português para retomar estudos",
    },
    prioridade: "urgente",
    responsavel: "Tiago",
    observacoes: "Prazo de renovação do protocolo neste mês.",
    status: "encaminhado",
    criadoEm: "2026-09-02T17:40:00.000Z",
    demo: true,
  },
  {
    id: "demo-3",
    nome: "Rosa M.",
    nacionalidade: "Venezuela",
    idioma: "Espanhol",
    contato: "rosa.demo@exemplo.org",
    acolhedor: "Beatriz",
    situacaoDocumental: "Documentação regular",
    demandas: ["saude", "assistencia"],
    respostas: {
      "saude.acesso": "Sim",
      "saude.obs": "Precisa de referência da UBS mais próxima",
      "assistencia.servico": "Não sabe",
    },
    prioridade: "atencao",
    responsavel: "Beatriz",
    status: "triado",
    criadoEm: "2026-09-02T14:05:00.000Z",
    demo: true,
  },
  {
    id: "demo-4",
    nome: "Daniel O.",
    nacionalidade: "Angola",
    idioma: "Português",
    acolhedor: "Marina",
    situacaoDocumental: "Protocolo/documento provisório",
    demandas: ["trabalho", "moradia"],
    respostas: {
      "trabalho.trabalhando": "Sim",
      "trabalho.necessidade": "Carteira assinada e registro profissional",
      "moradia.necessidade": "Aluguel compartilhado na região central",
    },
    prioridade: "normal",
    responsavel: "Marina",
    status: "encaminhado",
    criadoEm: "2026-09-01T19:20:00.000Z",
    demo: true,
  },
  {
    id: "demo-5",
    nome: "Lin W.",
    nacionalidade: "China",
    idioma: "Mandarim",
    acolhedor: "Tiago",
    situacaoDocumental: "Documentação regular",
    demandas: ["documentacao", "juridico"],
    respostas: {
      "documentacao.situacao": "Atualização de endereço no RNM",
      "documentacao.prazo": "Não sabe",
      "juridico.area": "Contrato de trabalho não cumprido",
    },
    prioridade: "normal",
    responsavel: "Ana",
    status: "triado",
    criadoEm: "2026-09-01T15:00:00.000Z",
    demo: true,
  },
  {
    id: "demo-6",
    nome: "Fatou D.",
    nacionalidade: "Senegal",
    idioma: "Wolof",
    acolhedor: "Ana",
    situacaoDocumental: "Sem documentação regular",
    demandas: ["documentacao", "assistencia", "trabalho"],
    respostas: {
      "documentacao.situacao": "Precisa iniciar processo de regularização",
      "documentacao.prazo": "Sim",
      "assistencia.servico": "Não",
      "trabalho.trabalhando": "Não",
      "trabalho.necessidade": "Encaminhamento para vaga informal imediata",
    },
    prioridade: "urgente",
    responsavel: "Ana",
    observacoes: "Chegou há duas semanas, sem rede de apoio na cidade.",
    status: "novo",
    criadoEm: "2026-08-31T18:30:00.000Z",
    demo: true,
  },
  {
    id: "demo-7",
    nome: "Carlos P.",
    nacionalidade: "Bolívia",
    idioma: "Espanhol",
    acolhedor: "Beatriz",
    situacaoDocumental: "Documentação regular",
    demandas: ["diploma"],
    respostas: {
      "diploma.pais": "Bolívia",
      "diploma.nivel": "Graduação",
      "diploma.possui": "Sim",
      "diploma.objetivo": "Informação",
    },
    prioridade: "normal",
    responsavel: "Beatriz",
    observacoes: "Orientado sobre o fluxo de revalidação em universidade pública.",
    status: "concluido",
    criadoEm: "2026-08-30T16:15:00.000Z",
    demo: true,
  },
];
